"""
Optional portfolio reporting - generates additional artifacts when enabled.

Only active when AXIOM_BT_PORTFOLIO_REPORT=1 environment variable is set.
"""

import os
import json
from pathlib import Path
from typing import Optional
import pandas as pd

from axiom_bt.portfolio.ledger import PortfolioLedger


def should_generate_report() -> bool:
    """Check if portfolio reporting is enabled via environment variable."""
    return os.getenv("AXIOM_BT_PORTFOLIO_REPORT") == "1"


def generate_portfolio_artifacts(
    ledger: PortfolioLedger,
    run_dir: Path,
    trades_df: Optional[pd.DataFrame] = None
) -> None:
    """
    Generate optional portfolio reporting artifacts.
    
    Only generates files if AXIOM_BT_PORTFOLIO_REPORT=1.
    
    Args:
        ledger: PortfolioLedger instance
        run_dir: Path to run directory
        trades_df: Optional trades DataFrame for additional stats
    """
    if not should_generate_report():
        return  # Silently skip if flag not set
    
    # Get summary stats
    summary = ledger.summary()
    
    # 1) portfolio_ledger.csv
    ledger_df = ledger.to_frame()
    ledger_path = run_dir / "portfolio_ledger.csv"
    ledger_df.to_csv(ledger_path, index=False)
    
    # 2) portfolio_summary.json
    summary_json = {
        **summary,
        "max_drawdown": _calculate_max_drawdown(ledger_df),
        "num_entries": len(ledger.entries)
    }
    
    # Add trade-specific stats if available
    if trades_df is not None and not trades_df.empty:
        summary_json["trades"] = {
            "count": len(trades_df),
            "wins": int((trades_df["pnl"] > 0).sum()),
            "losses": int((trades_df["pnl"] < 0).sum()),
            "win_rate": float((trades_df["pnl"] > 0).mean()),
        }
        
        # Breakdown by exit reason if available
        if "reason" in trades_df.columns:
            reason_counts = trades_df["reason"].value_counts().to_dict()
            summary_json["exit_reasons"] = {k: int(v) for k, v in reason_counts.items()}
    
    summary_path = run_dir / "portfolio_summary.json"
    with open(summary_path, 'w') as f:
        json.dump(summary_json, f, indent=2)
    
    # 3) portfolio_report.md (human readable)
    report_md = _generate_markdown_report(summary_json, ledger)
    report_path = run_dir / "portfolio_report.md"
    with open(report_path, 'w') as f:
        f.write(report_md)


def _calculate_max_drawdown(ledger_df: pd.DataFrame) -> float:
    """Calculate maximum drawdown from equity curve."""
    if len(ledger_df) <= 1:
        return 0.0
    
    equity = ledger_df["equity_after"]
    peak = equity.expanding().max()
    drawdown = (equity - peak) / peak
    return float(drawdown.min() * 100)  # Return as percentage


def _generate_markdown_report(summary: dict, ledger: PortfolioLedger) -> str:
    """Generate human-readable markdown report."""
    report = f"""# Portfolio Ledger Report

## Summary

| Metric | Value |
|:-------|:------|
| **Initial Cash** | ${summary['initial_cash']:.2f} |
| **Final Cash** | ${summary['final_cash']:.2f} |
| **Total PnL** | ${summary['total_pnl']:.2f} ({summary['total_pnl']/summary['initial_cash']*100:.2f}%) |
| **Peak Equity** | ${summary['peak_equity']:.2f} |
| **Max Drawdown** | {summary.get('max_drawdown', 0):.2f}% |

## Costs

| Type | Amount |
|:-----|:-------|
| **Total Fees** | ${summary['total_fees']:.2f} |
| **Total Slippage** | ${summary['total_slippage']:.2f} |
| **Combined Costs** | ${summary['total_fees'] + summary['total_slippage']:.2f} |

## Activity

- **Events**: {summary['num_events']} (excl. START)
- **Ledger Entries**: {summary.get('num_entries', 0)}

"""
    
    # Add trade stats if available
    if "trades" in summary:
        trades = summary["trades"]
        report += f"""## Trade Statistics

- **Total Trades**: {trades['count']}
- **Wins**: {trades['wins']} ({trades['win_rate']*100:.1f}%)
- **Losses**: {trades['losses']}

"""
    
    # Add exit reason breakdown if available
    if "exit_reasons" in summary:
        report += "### Exit Reasons\n\n"
        for reason, count in summary["exit_reasons"].items():
            report += f"- **{reason}**: {count}\n"
        report += "\n"
    
    report += """---

*Report generated by PortfolioLedger (AXIOM_BT_PORTFOLIO_REPORT=1)*
"""
    
    return report
