#!/bin/bash
# vendor_strategy.sh - Automate strategy vendoring from traderunner to marketdata-stream
#
# Usage: ./vendor_strategy.sh <strategy> <version>
# Example: ./vendor_strategy.sh inside_bar 2.1.0
#
# This script:
# 1. Validates version matches in core.py
# 2. Copies core files to marketdata-stream
# 3. Creates version marker
# 4. Commits to both repos with matching tags
# 5. Optionally pushes tags to GitHub

set -e  # Exit on any error

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Check arguments
if [ -z "$1" ] || [ -z "$2" ]; then
    echo "Usage: $0 <strategy> <version>"
    echo "Example: $0 inside_bar 2.1.0"
    exit 1
fi

STRATEGY=$1
VERSION=$2

echo -e "${GREEN}🔄 Vendoring ${STRATEGY} v${VERSION}...${NC}"

# Paths
TR_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
MD_ROOT="${TR_ROOT}/../marketdata-stream"
STRATEGY_DIR="${TR_ROOT}/src/strategies/${STRATEGY}"
VENDOR_DIR="${MD_ROOT}/src/unified_core"

# Validate paths exist
if [ ! -d "$STRATEGY_DIR" ]; then
    echo -e "${RED}❌ Strategy not found: ${STRATEGY_DIR}${NC}"
    exit 1
fi

if [ ! -d "$MD_ROOT" ]; then
    echo -e "${RED}❌ marketdata-stream not found: ${MD_ROOT}${NC}"
    exit 1
fi

# Extract version from core.py __version__ constant
echo -e "${YELLOW}📋 Checking version in core.py...${NC}"
CORE_VERSION=$(grep '^__version__ = ' "${STRATEGY_DIR}/core.py" | cut -d'"' -f2)

if [ -z "$CORE_VERSION" ]; then
    echo -e "${RED}❌ Could not find __version__ in core.py${NC}"
    exit 1
fi

echo "   core.py declares: ${CORE_VERSION}"
echo "   requested version: ${VERSION}"

# Verify versions match
if [ "$CORE_VERSION" != "$VERSION" ]; then
    echo -e "${RED}❌ Version mismatch!${NC}"
    echo "   core.py has __version__ = \"${CORE_VERSION}\""
    echo "   but you requested version ${VERSION}"
    echo ""
    echo "Please update __version__ in core.py first, or use version ${CORE_VERSION}"
    exit 1
fi

echo -e "${GREEN}✅ Version alignment OK${NC}"

# Copy core files
echo -e "${YELLOW}📦 Copying core files...${NC}"

if [ ! -d "$VENDOR_DIR" ]; then
    mkdir -p "$VENDOR_DIR"
    touch "${VENDOR_DIR}/__init__.py"
fi

cp "${STRATEGY_DIR}/core.py" "${VENDOR_DIR}/core.py"
echo "   Copied: core.py"

if [ -f "${STRATEGY_DIR}/config.py" ]; then
    cp "${STRATEGY_DIR}/config.py" "${VENDOR_DIR}/config.py"
    echo "   Copied: config.py"
fi

# Create version marker
echo -e "${YELLOW}🏷️  Creating version marker...${NC}"
cat > "${VENDOR_DIR}/version.py" <<EOF
"""Version marker for vendored strategy."""

VENDORED_VERSION = "${VERSION}"
VENDORED_STRATEGY = "${STRATEGY}"
VENDORED_FROM = "traderunner"
VENDORED_AT = "$(date -u +%Y-%m-%dT%H:%M:%SZ)"
VENDORED_BY = "$(git config user.name)"

# This file is auto-generated by vendor_strategy.sh
# DO NOT EDIT MANUALLY
EOF

echo "   Created: version.py"

# Calculate checksums for verification
TR_CHECKSUM=$(sha256sum "${STRATEGY_DIR}/core.py" | awk '{print $1}' | cut -c1-16)
MD_CHECKSUM=$(sha256sum "${VENDOR_DIR}/core.py" | awk '{print $1}' | cut -c1-16)

echo -e "${YELLOW}🔐 Checksums:${NC}"
echo "   traderunner:       ${TR_CHECKSUM}"
echo "   marketdata-stream: ${MD_CHECKSUM}"

if [ "$TR_CHECKSUM" != "$MD_CHECKSUM" ]; then
    echo -e "${RED}❌ Checksum mismatch after copy!${NC}"
    exit 1
fi

echo -e "${GREEN}✅ Files copied successfully${NC}"

# Git operations
echo -e "${YELLOW}💾 Committing to repositories...${NC}"

# Commit to traderunner
cd "$TR_ROOT"
if git status --porcelain | grep -q "src/strategies/${STRATEGY}"; then
    git add "src/strategies/${STRATEGY}/"
    git commit -m "release(${STRATEGY}): v${VERSION} ready for deployment

- Version: ${VERSION}
- Checksum: ${TR_CHECKSUM}
- Ready for vendoring to marketdata-stream"
    
    git tag "${STRATEGY}-v${VERSION}"
    echo -e "${GREEN}✅ traderunner: committed and tagged${NC}"
else
    echo "   traderunner: no changes to commit"
fi

# Commit to marketdata-stream
cd "$MD_ROOT"
git add src/unified_core/
git commit -m "vendor(${STRATEGY}): v${VERSION} from traderunner

- Vendored from: traderunner/${STRATEGY}
- Version: ${VERSION}
- Checksum: ${MD_CHECKSUM}
- Timestamp: $(date -u +%Y-%m-%dT%H:%M:%SZ)"

git tag "${STRATEGY}-vendor-v${VERSION}"
echo -e "${GREEN}✅ marketdata-stream: committed and tagged${NC}"

# Summary
echo ""
echo -e "${GREEN}✅ Vendoring complete!${NC}"
echo ""
echo "Summary:"
echo "  Strategy:       ${STRATEGY}"
echo "  Version:        ${VERSION}"
echo "  Checksum:       ${TR_CHECKSUM}"
echo ""
echo "Git tags created:"
echo "  traderunner:       ${STRATEGY}-v${VERSION}"
echo "  marketdata-stream: ${STRATEGY}-vendor-v${VERSION}"
echo ""
echo "Next steps:"
echo "  1. Review changes:"
echo "     cd ${TR_ROOT} && git show ${STRATEGY}-v${VERSION}"
echo "     cd ${MD_ROOT} && git show ${STRATEGY}-vendor-v${VERSION}"
echo ""
echo "  2. Push to GitHub:"
echo "     cd ${TR_ROOT} && git push --follow-tags"
echo "     cd ${MD_ROOT} && git push --follow-tags"
echo ""
echo "  3. Deploy to server:"
echo "     cd ${MD_ROOT}/deployment"
echo "     ansible-playbook playbooks/deploy.yml -i inventory/test.yml"
